import {
  Courgette,
  Playwrite_IN,
  Delius,
  Monsieur_La_Doulaise,
} from "next/font/google";
import "./globals.css";
import Navbar from "./navigation";

const courgette = Courgette({
  variable: "--font-courgette",
  subsets: ["latin"],
  weight: "400",
  display: "swap",
});

const playwrite_IN = Playwrite_IN({
  variable: "--font-playwrite",
  subsets: ["latin"],
  weight: "400",
  display: "swap",
});

const delius = Delius({
  variable: "--font-delius",
  subsets: ["latin"],
  weight: "400",
  display: "swap",
});

const monsieur_La_Doulaise = Monsieur_La_Doulaise({
  variable: "--font-monsieur-la-doulaise",
  subsets: ["latin"],
  weight: "400",
  display: "swap",
});

export const metadata = {
  title: "Taste Forge",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${courgette.variable} ${playwrite_IN.variable} ${delius.variable} ${monsieur_La_Doulaise.variable} antialiased ${courgette.className}`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
